# Bitácora de ejercicios

#### INSTITUTO TECNOLÓGICO SUPERIOR DE VALLADOLID

##### Docente: M.M. Jorge Manuel Pool Cen

##### Alumna: Lourdes Judith Kanxoc Hau-19070071

##### Aignatura: Métodos Numéricos

##### Unidad 2

##### Actividad 2.1:Métodos de solución de ecuaciones

##### 4°A

##### Fecha de entrega: 21 de abril de 2021

### Ejercicio 1. Determinar una raíz para  f(x)=tan⁡(x)-3.5 en el intervalo [0,π] con una tolerancia de 0.05.

##### Método de bisección

In [1]:
import numpy as np
import math
from math import pi

# INGRESO
fx = lambda x: math.cos(x)-3.5
a = 0
b = pi
tolera = 0.05

# PROCEDIMIENTO
tabla = []
tramo = b-a

fa = fx(a)
fb = fx(b)
i = 1
while (tramo>tolera):
    c = (a+b)/2
    fc = fx(c)
    tabla.append([i,a,c,b,fa,fc,fb,tramo])
    i = i + 1
                 
    cambia = np.sign(fa)*np.sign(fc)
    if (cambia<0):
        b = c
        fb = fc
    else:
        a=c
        fa = fc
    tramo = b-a
c = (a+b)/2
fc = fx(c)
tabla.append([i,a,c,b,fa,fc,fb,tramo])
tabla = np.array(tabla)

raiz = c

# SALIDA
np.set_printoptions(precision = 4)
print('[ i, a, c, b, f(a), f(c), f(b), tramo]')
# print(tabla)

# Tabla con formato
n=len(tabla)
for i in range(0,n,1):
    unafila = tabla[i]
    formato = '{:.0f}'+' '+(len(unafila)-1)*'{:.6f} '
    unafila = formato.format(*unafila)
    print(unafila)
    
print('raiz: ',raiz)

[ i, a, c, b, f(a), f(c), f(b), tramo]
1 0.000000 1.570796 3.141593 -2.500000 -3.500000 -4.500000 3.141593 
2 1.570796 2.356194 3.141593 -3.500000 -4.207107 -4.500000 1.570796 
3 2.356194 2.748894 3.141593 -4.207107 -4.423880 -4.500000 0.785398 
4 2.748894 2.945243 3.141593 -4.423880 -4.480785 -4.500000 0.392699 
5 2.945243 3.043418 3.141593 -4.480785 -4.495185 -4.500000 0.196350 
6 3.043418 3.092505 3.141593 -4.495185 -4.498795 -4.500000 0.098175 
7 3.092505 3.117049 3.141593 -4.498795 -4.499699 -4.500000 0.049087 
raiz:  3.117048960983623


### Ejercicio 2. Un proyectil de M=2 gm se ha lanzado en forma vertical al aire y está descendiendo a su velocidad terminal. Dicha velocidad se determina mediante la ecuación gM=Ddrag donde g es la gravedad y M es la masa; esta ecuación se puede escribir después de evaluar las constantes como (29.81)/1000=1.410^(-5) v^1.5+1.15*10^(-5) v^2
### Donde v es la velocidad terminal en m/seg. El primer término del lado derecho representa la fuerza de fricción y el segundo la fuerza de la presión. Determinar la velocidad terminal mediante el método de bisección con una tolerancia de 0.001.
#### Método de bisección


In [2]:
import numpy as np

# INGRESO
fx = lambda x: -0.0000115*x**2 - 0.000014*x**(1.5)+0.01962
a = 30
b = 40
tolera = 0.001

# PROCEDIMIENTO
tabla = []
tramo = b-a

fa = fx(a)
fb = fx(b)
i = 1
while (tramo>tolera):
    c = (a+b)/2
    fc = fx(c)
    tabla.append([i,a,c,b,fa,fc,fb,tramo])
    i = i + 1
                 
    cambia = np.sign(fa)*np.sign(fc)
    if (cambia<0):
        b = c
        fb = fc
    else:
        a=c
        fa = fc
    tramo = b-a
c = (a+b)/2
fc = fx(c)
tabla.append([i,a,c,b,fa,fc,fb,tramo])
tabla = np.array(tabla)

raiz = c

# SALIDA
np.set_printoptions(precision = 4)
print('[ i, a, c, b, f(a), f(c), f(b), tramo]')
# print(tabla)

# Tabla con formato
n=len(tabla)
for i in range(0,n,1):
    unafila = tabla[i]
    formato = '{:.0f}'+' '+(len(unafila)-1)*'{:.3f} '
    unafila = formato.format(*unafila)
    print(unafila)
    
print('raiz: ',raiz)

[ i, a, c, b, f(a), f(c), f(b), tramo]
1 30.000 35.000 40.000 0.007 0.003 -0.002 10.000 
2 35.000 37.500 40.000 0.003 0.000 -0.002 5.000 
3 37.500 38.750 40.000 0.000 -0.001 -0.002 2.500 
4 37.500 38.125 38.750 0.000 -0.000 -0.001 1.250 
5 37.500 37.812 38.125 0.000 -0.000 -0.000 0.625 
6 37.500 37.656 37.812 0.000 0.000 -0.000 0.312 
7 37.656 37.734 37.812 0.000 0.000 -0.000 0.156 
8 37.734 37.773 37.812 0.000 -0.000 -0.000 0.078 
9 37.734 37.754 37.773 0.000 -0.000 -0.000 0.039 
10 37.734 37.744 37.754 0.000 -0.000 -0.000 0.020 
11 37.734 37.739 37.744 0.000 -0.000 -0.000 0.010 
12 37.734 37.737 37.739 0.000 -0.000 -0.000 0.005 
13 37.734 37.736 37.737 0.000 -0.000 -0.000 0.002 
14 37.734 37.735 37.736 0.000 -0.000 -0.000 0.001 
15 37.734 37.735 37.735 0.000 -0.000 -0.000 0.001 
raiz:  37.73468017578125


### Ejercicio 3. Encuentre la raíz de f(x)=tan⁡(x)-0.1x en el intervalo [π,1.5π] mediante el método de newton con una tolerancia de 0.0001
#### Método de bisección

In [3]:
import numpy as np
import math
from math import pi

# INGRESO
fx = lambda x: math.tan(x)-0.1*x
a = pi
b = 1.5*pi
tolera = 0.0001

# PROCEDIMIENTO
tabla = []
tramo = b-a

fa = fx(a)
fb = fx(b)
i = 1
while (tramo>tolera):
    c = (a+b)/2
    fc = fx(c)
    tabla.append([i,a,c,b,fa,fc,fb,tramo])
    i = i + 1
                 
    cambia = np.sign(fa)*np.sign(fc)
    if (cambia<0):
        b = c
        fb = fc
    else:
        a=c
        fa = fc
    tramo = b-a
c = (a+b)/2
fc = fx(c)
tabla.append([i,a,c,b,fa,fc,fb,tramo])
tabla = np.array(tabla)

raiz = c

# SALIDA
np.set_printoptions(precision = 4)
print('[ i, a, c, b, f(a), f(c), f(b), tramo]')
# print(tabla)

# Tabla con formato
n=len(tabla)
for i in range(0,n,1):
    unafila = tabla[i]
    formato = '{:.0f}'+' '+(len(unafila)-1)*'{:.3f} '
    unafila = formato.format(*unafila)
    print(unafila)
    
print('raiz: ',raiz)

[ i, a, c, b, f(a), f(c), f(b), tramo]
1 3.142 3.927 4.712 -0.314 0.607 5443746451065123.000 1.571 
2 3.142 3.534 3.927 -0.314 0.061 0.607 0.785 
3 3.142 3.338 3.534 -0.314 -0.135 0.061 0.393 
4 3.338 3.436 3.534 -0.135 -0.040 0.061 0.196 
5 3.436 3.485 3.534 -0.040 0.009 0.061 0.098 
6 3.436 3.461 3.485 -0.040 -0.016 0.009 0.049 
7 3.461 3.473 3.485 -0.016 -0.003 0.009 0.025 
8 3.473 3.479 3.485 -0.003 0.003 0.009 0.012 
9 3.473 3.476 3.479 -0.003 -0.000 0.003 0.006 
10 3.476 3.478 3.479 -0.000 0.001 0.003 0.003 
11 3.476 3.477 3.478 -0.000 0.001 0.001 0.002 
12 3.476 3.476 3.477 -0.000 0.000 0.001 0.001 
13 3.476 3.476 3.476 -0.000 0.000 0.000 0.000 
14 3.476 3.476 3.476 -0.000 -0.000 0.000 0.000 
15 3.476 3.476 3.476 -0.000 0.000 0.000 0.000 
raiz:  3.4761442760477266


### Ejercicio 4. Hallé la raíz de la función  f(x)=x^4-2x^3-4x^2+4=0, en las regiones. Utilice un 0.001 de error (esta en relativo, no en porcentual)
a =	[-2,-1]
#### Método de bisección

In [ ]:
import numpy as np

# INGRESO
fx = lambda x: x**4 -2*(x**3)-4*(x**2)+4
a = -2
b = -1
tolera = 0.001

# PROCEDIMIENTO
tabla = []
tramo = b-a

fa = fx(a)
fb = fx(b)
i = 1
while (tramo>tolera):
    c = (a+b)/2
    fc = fx(c)
    tabla.append([i,a,c,b,fa,fc,fb,tramo])
    i = i + 1
                 
    cambia = np.sign(fa)*np.sign(fc)
    if (cambia<0):
        b = c
        fb = fc
    else:
        a=c
        fa = fc
    tramo = b-a
c = (a+b)/2
fc = fx(c)
tabla.append([i,a,c,b,fa,fc,fb,tramo])
tabla = np.array(tabla)

raiz = c

# SALIDA
np.set_printoptions(precision = 4)
print('[ i, a, c, b, f(a), f(c), f(b), tramo]')
# print(tabla)

# Tabla con formato
n=len(tabla)
for i in range(0,n,1):
    unafila = tabla[i]
    formato = '{:.0f}'+' '+(len(unafila)-1)*'{:.3f} '
    unafila = formato.format(*unafila)
    print(unafila)
    
print('raiz: ',raiz)

### Ejercicio 5. Hallé la raíz de la función  f(x)=x^4-2x^3-4x^2+4=0, en las regiones. Utilice un 0.001 de error (esta en relativo, no en porcentual)
b =	[0,2]
#### Método de bisección

In [ ]:
import numpy as np

# INGRESO
fx = lambda x: x**4 -2*(x**3)-4*(x**2)+4
a = 0
b = 2
tolera = 0.001

# PROCEDIMIENTO
tabla = []
tramo = b-a

fa = fx(a)
fb = fx(b)
i = 1
while (tramo>tolera):
    c = (a+b)/2
    fc = fx(c)
    tabla.append([i,a,c,b,fa,fc,fb,tramo])
    i = i + 1
                 
    cambia = np.sign(fa)*np.sign(fc)
    if (cambia<0):
        b = c
        fb = fc
    else:
        a=c
        fa = fc
    tramo = b-a
c = (a+b)/2
fc = fx(c)
tabla.append([i,a,c,b,fa,fc,fb,tramo])
tabla = np.array(tabla)

raiz = c

# SALIDA
np.set_printoptions(precision = 4)
print('[ i, a, c, b, f(a), f(c), f(b), tramo]')
# print(tabla)

# Tabla con formato
n=len(tabla)
for i in range(0,n,1):
    unafila = tabla[i]
    formato = '{:.0f}'+' '+(len(unafila)-1)*'{:.3f} '
    unafila = formato.format(*unafila)
    print(unafila)
    
print('raiz: ',raiz)

### Ejercicio 6. Hallé la raíz de la función  f(x)=tan⁡x, en las región [4,4.5]. Considere un error del 0.001.
##### Método de bisección

In [4]:
import numpy as np
import math
from math import pi

# INGRESO
fx = lambda x: x-math.tan(x)
a = 4
b = 4.5
tolera = 0.001

# PROCEDIMIENTO
tabla = []
tramo = b-a

fa = fx(a)
fb = fx(b)
i = 1
while (tramo>tolera):
    c = (a+b)/2
    fc = fx(c)
    tabla.append([i,a,c,b,fa,fc,fb,tramo])
    i = i + 1
                 
    cambia = np.sign(fa)*np.sign(fc)
    if (cambia<0):
        b = c
        fb = fc
    else:
        a=c
        fa = fc
    tramo = b-a
c = (a+b)/2
fc = fx(c)
tabla.append([i,a,c,b,fa,fc,fb,tramo])
tabla = np.array(tabla)

raiz = c

# SALIDA
np.set_printoptions(precision = 4)
print('[ i, a, c, b, f(a), f(c), f(b), tramo]')
# print(tabla)

# Tabla con formato
n=len(tabla)
for i in range(0,n,1):
    unafila = tabla[i]
    formato = '{:.0f}'+' '+(len(unafila)-1)*'{:.6f} '
    unafila = formato.format(*unafila)
    print(unafila)
    
print('raiz: ',raiz)

[ i, a, c, b, f(a), f(c), f(b), tramo]
1 4.000000 4.250000 4.500000 2.842179 2.243691 -0.137332 0.500000 
2 4.250000 4.375000 4.500000 2.243691 1.524388 -0.137332 0.250000 
3 4.375000 4.437500 4.500000 1.524388 0.891762 -0.137332 0.125000 
4 4.437500 4.468750 4.500000 0.891762 0.445853 -0.137332 0.062500 
5 4.468750 4.484375 4.500000 0.445853 0.174948 -0.137332 0.031250 
6 4.484375 4.492188 4.500000 0.174948 0.024531 -0.137332 0.015625 
7 4.492188 4.496094 4.500000 0.024531 -0.054892 -0.137332 0.007812 
8 4.492188 4.494141 4.496094 0.024531 -0.014814 -0.054892 0.003906 
9 4.492188 4.493164 4.494141 0.024531 0.004949 -0.014814 0.001953 
10 4.493164 4.493652 4.494141 0.004949 -0.004910 -0.014814 0.000977 
raiz:  4.49365234375


### Ejercicio 7. Utilice Xo=1 y determina la raíz con un error de 0.01 de la función x^4-3x^2-3.
#### Método de Newtón

In [5]:
import numpy as np

# INGRESO
fx  = lambda x: x**4 - 3*(x**2) - 3
dfx = lambda x: 4*(x**3) + 6*x

x0 = 1
tolera = 0.01

# PROCEDIMIENTO
tabla = []
tramo = abs(2*tolera)
xi = x0
while (tramo>=tolera):
    xnuevo = xi - fx(xi)/dfx(xi)
    tramo  = abs(xnuevo-xi)
    tabla.append([xi,xnuevo,tramo])
    xi = xnuevo

# convierte la lista a un arreglo.
tabla = np.array(tabla)
n = len(tabla)

# SALIDA
print(['xi', 'xnuevo', 'tramo'])
np.set_printoptions(precision = 4)
print(tabla)
print('raiz en: ', xi)
print('con error de: ',tramo)



['xi', 'xnuevo', 'tramo']
[[1.     1.5    0.5   ]
 [1.5    1.7083 0.2083]
 [1.7083 1.8156 0.1072]
 [1.8156 1.8737 0.0581]
 [1.8737 1.9058 0.0322]
 [1.9058 1.9238 0.018 ]
 [1.9238 1.9339 0.0101]
 [1.9339 1.9397 0.0057]]
raiz en:  1.9396592714865175
con error de:  0.00571955370608257


### Ejercicio 8. Utilice Xo=1 y determina la raíz con un error de 0.01 de la función 2 sen πx+x=0.
#### Método de Newtón

In [6]:
import numpy as np

# INGRESO
fx  = lambda x: 2*math.sin(math.pi*x)+x
dfx = lambda x: 2*math.pi*math.cos(math.pi*x)+1


x0 = 1
tolera = 0.01

# PROCEDIMIENTO
tabla = []
tramo = abs(2*tolera)
xi = x0
while (tramo>=tolera):
    xnuevo = xi - fx(xi)/dfx(xi)
    tramo  = abs(xnuevo-xi)
    tabla.append([xi,xnuevo,tramo])
    xi = xnuevo

# convierte la lista a un arreglo.
tabla = np.array(tabla)
n = len(tabla)

# SALIDA
print(['xi', 'xnuevo', 'tramo'])
np.set_printoptions(precision = 4)
print(tabla)
print('raiz en: ', xi)
print('con error de: ',tramo)

['xi', 'xnuevo', 'tramo']
[[1.0000e+00 1.1893e+00 1.8928e-01]
 [1.1893e+00 1.2057e+00 1.6377e-02]
 [1.2057e+00 1.2060e+00 3.7845e-04]]
raiz en:  1.2060349073454595
con error de:  0.00037844893195737583


### Ejercicio 9. Sea f(x)=x^2-6, y utilice x0=1 para determinar la raíz, considere un error del 0.001
#### Método de Newtón

In [ ]:
import numpy as np

# INGRESO
fx  = lambda x: x**2 - 6
dfx = lambda x: 2*x

x0 = 1
tolera = 0.001

# PROCEDIMIENTO
tabla = []
tramo = abs(2*tolera)
xi = x0
while (tramo>=tolera):
    xnuevo = xi - fx(xi)/dfx(xi)
    tramo  = abs(xnuevo-xi)
    tabla.append([xi,xnuevo,tramo])
    xi = xnuevo

# convierte la lista a un arreglo.
tabla = np.array(tabla)
n = len(tabla)

# SALIDA
print(['xi', 'xnuevo', 'tramo'])
np.set_printoptions(precision = 10)
print(tabla)
print('raiz en: ', xi)
print('con error de: ',tramo)

### Ejercicio 10. Sea f(x)=〖-x〗^3-cos⁡x, y utilice x0=--1 para determinar la raíz, considere un error del 0.001
#### Método de Newtón

In [ ]:
import numpy as np

# INGRESO
fx  = lambda x: -math.cos(x)-x**3
dfx = lambda x: -3*x**2+ math.sin(x)

x0 = -1
tolera = 0.001

# PROCEDIMIENTO
tabla = []
tramo = abs(2*tolera)
xi = x0
while (tramo>=tolera):
    xnuevo = xi - fx(xi)/dfx(xi)
    tramo  = abs(xnuevo-xi)
    tabla.append([xi,xnuevo,tramo])
    xi = xnuevo

# convierte la lista a un arreglo.
tabla = np.array(tabla)
n = len(tabla)

# SALIDA
print(['xi', 'xnuevo', 'tramo'])
np.set_printoptions(precision = 4)
print(tabla)
print('raiz en: ', xi)
print('con error de: ',tramo)

### Ejercicio 11. Sea f(x)=〖-x〗^3-cos⁡x, y utilice x0=--1, x1=1 para determinar la raíz, considere un error del 0.001
### Método de secante

In [11]:
import numpy as np

def secante_tabla(fx,xa,tolera):
    dx = 6*tolera
    xb = xa + dx
    tramo = dx
    tabla = []
    while (tramo>=tolera):
        fa = fx(xa)
        fb = fx(xb)
        xc = xa - fa*(xb-xa)/(fb-fa)
        tramo = abs(xc-xa)
        
        tabla.append([xa,xb,xc,tramo])
        xb = xa
        xa = xc

    tabla = np.array(tabla)
    return(tabla)

# PROGRAMA ---------------------
# INGRESO
fx = lambda x: -math.cos(x)-x**3

a  = 1
b  = 1
xa = -1
tolera = 0.001
tramos = 100

# PROCEDIMIENTO
tabla = secante_tabla(fx,xa,tolera)
n = len(tabla)
raiz = tabla[n-1,2]

# SALIDA
np.set_printoptions(precision=4)
print('[xa ,\t xb , \t xc , \t tramo]')
for i in range(0,n,1):
    print(tabla[i])
print('raiz en: ', raiz)

[xa ,	 xb , 	 xc , 	 tramo]
[-1.     -0.994  -0.8797  0.1203]
[-0.8797 -1.     -0.8672  0.0126]
[-0.8672 -0.8797 -0.8655  0.0017]
[-8.6550e-01 -8.6716e-01 -8.6547e-01  2.3071e-05]
raiz en:  -0.8654740709464117
